main: com.github.xaxys.metro.Main
name: Metro
version: 1.4.1
author: xaxys
api-version: 1.13
description: Adds Working Metro to Minecraft!
commands:
  metro:
    description: Metro Plugin Command.
    usage: /metro
permissions:
  metro.speed:
    description: Allows you to change the speed of a metro line.
    default: op
  metro.create:
    description: Allow player to create or destroy a metro station.
    default: op
  metro.use:
    description: Allow player to use a metro station.
    default: true
  metro.reload:
    description: Reload the plugin.
    default: op
